### ISSUE TITLE
 [NGINX] Error fetching stats

### ISSUE THREAD

**Issue by KillaDreams** [715209/nginx-obs-automatic-low-bitrate-switching#10]
over 2 weeks of work on this and I believe that this is the last step to getting this working 100%. 
 I have gone through all that I can and have had no luck fixing [NGINX] Error fetching stats.

I've attached my nginx.conf file i can access the http://10.0.0.193:8080/stat page just fine and see the info there but  [OBS] » ×  error     [NGINX] Error fetching stats can't

[nginx conf.txt](https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/files/3478409/nginx.conf.txt)

**Comment by 715209** [comment]
Hello KillaDreams,

This issue is because of how i named the "rtmp" field [(this)](https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/blob/master/config.json#L15) you should be able to get this working by changing it to `rtmp://10.0.0.193:8080/publish/live`

**Comment by KillaDreams** [comment]
Upon doing that I get another error being thrown

[2019-08-08T18_57_09_715Z-debug.log](https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/files/3483274/2019-08-08T18_57_09_715Z-debug.log)
> node ./lib/app

internal/modules/cjs/loader.js:800
    throw err;
    ^

SyntaxError: C:\Users\cmfuk\Desktop\nginx-low\config.json: Unexpected token r in JSON at position 399
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:797:27)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\cmfuk\Desktop\nginx-low\lib\components\ObsSwitcher.js:14:38)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nginx-obs-automatic-low-bitrate-switching@1.3.0 start: `node ./lib/app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nginx-obs-automatic-low-bitrate-switching@1.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cmfuk\AppData\Roaming\npm-cache\_logs\2019-08-08T18_57_09_715Z-debug.log

**Comment by 715209** [comment]
Looks like something is wrong with your `config.json`

**Comment by KillaDreams** [comment]
yes i changed what was told to be changed as per above

**Comment by 715209** [comment]
Is it still not working?

**Comment by KillaDreams** [comment]
No is there a way I can just for the file to know exactly what the nginx server information 
is?

 https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/blob/4b3c702c99bd7725b105156e10b55233aa81ca7e/lib/components/ObsSwitcher.js#L184

**Comment by 715209** [comment]
It's here: https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/blob/4b3c702c99bd7725b105156e10b55233aa81ca7e/src/components/ObsSwitcher.js#L112

Probably should change the config one day.

**Comment by KillaDreams** [comment]
Yeah it was either one of those but can I input manually for the variables of this.ginxSettings

**Comment by 715209** [comment]
If you want we can talk in discord, 715209#0600

**Comment by Benjo1990** [comment]
@715209 i add you too

**Comment by Limestamp** [comment]
hi @715209 i have the same problem. and cant fix it. did you guys come up with a fix?
