### ISSUE TITLE
Nginx Error

### ISSUE THREAD

**Issue by AlphaKing112** [715209/nginx-obs-automatic-low-bitrate-switching#105]
automatic switching works but I get an error that says nginx: Error parsing stats (http://localhost/stats) missing field `codec` 
Does anybody know what this means?

**Comment by 715209** [comment]
Hi @AlphaKing112 ,

The next release is up here: [NOALBS v2.6.1](https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/releases/tag/v2.6.1). Can you confirm if this solves your issue.
