### ISSUE TITLE
Error reading the config folder with files without file extension

### ISSUE THREAD

**Issue by fbrettnich** [715209/nginx-obs-automatic-low-bitrate-switching#118]
Hi, I just restarted NOALBS and used the multi-user option with the configuration folder. By doing this, I received the error below.
After looking around, I found that the file `.DS_Store` (on MacOS) is present. I removed this for testing and now it works.

**Which means that files without extension trigger an error when checking them:**

https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/blob/ba68b5f2fdad77cd621f200327ae6715bb08980a/src/main.rs#L111

![image](https://user-images.githubusercontent.com/42101045/189739282-dde7826d-37c6-467f-88b9-d9cd35c617d1.png)

**Comment by 715209** [comment]
Hi @fbrettnich ,

Thanks for creating an issue, I'll fix this in the next version. 👍
