### ISSUE TITLE
No auto switcher chat notification from 2.7.2

### ISSUE THREAD

**Issue by thelegendtubaguy** [715209/nginx-obs-automatic-low-bitrate-switching#122]
Hey there, I'm  running noalbs 2.7.2 and noticing that I'm not getting any in chat notifications when the scene is switching.  I have the config file option set and I've also tried doing `!notify on`.  It responds and says `Auto switch notification is enabled` but it's not notifying when it switches scenes at all.

**Comment by Barrikin** [comment]
Check your OAuth's

**Comment by thelegendtubaguy** [comment]
Well I was getting chat messages, like I said it responded to me.  And I could run `!bitrate` and `!sourceinfo` just fine.

Looking through the code for 2.7.2 it doesn't look like that setting is used anywhere yet.  Maybe I'm not looking in the proper spot.

**Comment by DigibitDK** [comment]
Works for me. (2.7.2)

**Comment by thelegendtubaguy** [comment]
I looked further in to the switcher code and that appears to be only if OBS is streaming.  It'd be nice to have the option to enable it for testing purposes.

I'll close this though.  Thanks!

**Comment by 715209** [comment]
Hey @thelegendtubaguy ,

It only works when streaming from OBS to avoid sending messages when it's not really needed. If you're streaming to twitch you could just enable the bandwidth test mode or stream to your ingest.
