### ISSUE TITLE
enableAutoStopStreamOnHostOrRaid stopped working

### ISSUE THREAD

**Issue by Chucks1860** [715209/nginx-obs-automatic-low-bitrate-switching#123]
Hello there,

we've encountered the issue stated in the topic where noalbs doesn't stop the stream when raiding someone.
This started a short time ago but worked perfectly fine for a long time.

Can I do anything to fix this issue myself or is this problem even known or is it just an individual case for me?

We can do a workaround via Stream Deck Multiaction in the meantime but I'm curious if this issue is client side or maybe caused by the recent twitch changes (shoutouts, host function being shut off, etc. and thus maybe api changes?).

Thanks for your help in advance and for this wonderful tool you've created!!! :)

**Comment by 715209** [comment]
Hi @Chucks1860 ,

That feature relied on the message send from twitch when hosting, and since that has been removed it is not working anymore. I have a fix that relies on raid coming soon!

**Comment by Chucks1860** [comment]
Hi @715209 ,

I see! :)
Thanks for the info.
Really looking forward to it. :) 👍

**Comment by 715209** [comment]
Hi @Chucks1860 ,

This has finally been fixed, will be available in the next release or if you're building from source it's already available.
