### ISSUE TITLE
v2.7.3 - bot not posting scene name when switching scene

### ISSUE THREAD

**Issue by thegamingstig** [715209/nginx-obs-automatic-low-bitrate-switching#130]
Before 2.7.3 the bot would post the scene name in chat when switching between Live/Low bitrate/BRB. After 2.7.3, the bot only says it has change scene but doesn't say which scene I am in. Can you revert back to the old way?

![image](https://user-images.githubusercontent.com/97251471/204682044-0a8852dd-cef5-49a7-9364-af123b29705c.png)

**Comment by b3ck** [comment]
Re-download the v2.7.3 release, it has been fixed 👍
