### ISSUE TITLE
Please add support for other languages.

### ISSUE THREAD

**Issue by UnisonRU** [715209/nginx-obs-automatic-low-bitrate-switching#14]
Please add support for other languages.

**Comment by 715209** [comment]
Hello @UnisonRU, 

I've just added support for other chat messages (please open this issue again if I misunderstood).
Unfortunately I don't know your language so I can't translate the file.

If you are able to translate English to your language i would kindly want to ask if you can create a pull request with a file in your language in the locale folder.
