### ISSUE TITLE
Unable to display Chinese interface

### ISSUE THREAD

**Issue by doggycxj** [715209/nginx-obs-automatic-low-bitrate-switching#142]
I tried changing the “language” setting in the config.json file to “zh_tw”, “ZH_TW”, “zh_TW”, “ZH_tw”, “ZHTW” and “zhtw” but the interface still does not display in Chinese. Is there a way to use the Chinese interface?

**Comment by 715209** [comment]
Hi @doggycxj ,

You can just use the command `!noalbs lang zh_tw` to change the language.

**Comment by doggycxj** [comment]
Thank you very much
