### ISSUE TITLE
Adding support for MediaMTX

### ISSUE THREAD

**Issue by tompointexe** [715209/nginx-obs-automatic-low-bitrate-switching#144]
Hi, would it be possible to add support for MediaMTX, a free and opensource multi-purpose and format streaming server

https://github.com/bluenviron/mediamtx

Thanks a lot

**Comment by b3ck** [comment]
Does it have a way to read streams and see the bitrate?

**Comment by tompointexe** [comment]
I sadly don't think so
The API is documented here https://bluenviron.github.io/mediamtx/
but after a quick look, all endpoint we need are here, they just dont return the bitrate
Edit: Updated the api Link

**Comment by 715209** [comment]
Hi @tompointexe ,

Looks like it's possible to grab the `bytesReceived`, I'll have to calculate the bitrate from that.
