### ISSUE TITLE
live: stream not found, client:  

### ISSUE THREAD

**Issue by MiwiDots** [715209/nginx-obs-automatic-low-bitrate-switching#166]
Hi,

I have this wired error here, it runs just fine for an hour or so and then it lose the connection even thought everything seems to be fine.

2024/06/22 13:36:49 [error] 396#33040: *1089 live: stream not found, client: 127.0.0.1, server: 0.0.0.0:1935
2024/06/22 13:36:54 [error] 396#33040: *1090 live: stream not found, client: 127.0.0.1, server: 0.0.0.0:1935
2024/06/22 13:36:59 [error] 396#33040: *1091 live: stream not found, client: 127.0.0.1, server: 0.0.0.0:1935
2024/06/22 13:37:04 [error] 396#33040: *1092 live: stream not found, client: 127.0.0.1, server: 0.0.0.0:1935

Anyone have an advice for that?

**Comment by 715209** [comment]
Hi @miwi-fbsd ,

Where are you getting these errors from? And could you please tell me more about how your setup works.

**Comment by MiwiDots** [comment]
Hi,

IRL Setup (Mobile)
- Camera: GoPro 12 Black
- Connection: GoPro connected to mobile phone via hotspot
- Streaming Protocol: RTMP setup in the GoPro app
- Streaming Control: Using OBS-Blade to start/end the stream

Home Setup
-  DynDNS: Configured for remote access
- OBS: Running on home PC
- NGINX and noalbs: Downloaded and set up from the specified repository

Issue
The stream works fine initially but disconnects frequently between 50 and 55 minutes.
The GoPro displays a network error message.
NGINX logs show disconnection errors.

Thx for helping

//edit 
Maybe i should mention the 50 - 55 Min dc was most of the time in that time range, sometimes it was earlier. The other point is i can not reconnect to the stream without restarting nginx.


//edit 2

I just noted another thing

2024/06/22 12:13:53 [error] 396#33040: *47 live: already publishing, client: 183.171.xx.XX , server: 0.0.0.0:1935
2024/06/22 12:14:00 [error] 396#33040: *48 live: stream not found, client: 127.0.0.1, server: 0.0.0.0:1935
2024/06/22 12:14:05 [error] 396#33040: *49 live: stream not found, client: 127.0.0.1, server: 0.0.0.0:1935

this error seems to be the main cause after that it dies.

**Comment by 715209** [comment]
Have you setup NGINX with [the config](https://github.com/NOALBS/nginx-obs-automatic-low-bitrate-switching/blob/v2/nginx/conf/nginx.conf) provided in the repo?
It might just be that NGINX is not releasing the key which causes the `already publishing` error and preventing the GoPro from reconnecting, the linked config should prevent that.

**Comment by MiwiDots** [comment]
Apparently not I will give it a try thank you so  much!

**Comment by MiwiDots** [comment]
Seems to work way better thank you once again. Thanks for all the work u have put in here ;) cheers.

**Comment by 715209** [comment]
Glad it works! GoPros are notorious for randomly disconnecting.
