### ISSUE TITLE
NOALBS for Raspberry ARM.

### ISSUE THREAD

**Issue by Paul-Bommel** [715209/nginx-obs-automatic-low-bitrate-switching#168]
Hello, I have a question.

will there be a version of NOALBS in the future, supporting Raspberry Pi or ARM processors?

**Comment by 715209** [comment]
Hi @Paul-Bommel ,

You should be able to build NOALBS from source on the Raspberry Pi or ARM systems. Follow the instructions here [#building-from-source](https://github.com/NOALBS/nginx-obs-automatic-low-bitrate-switching?tab=readme-ov-file#building-from-source)
