### ISSUE TITLE
After using noalbs he often switches to brb

### ISSUE THREAD

**Issue by sungithub777** [715209/nginx-obs-automatic-low-bitrate-switching#175]
During testing, my noalbs often switches to brb. It can switch to various scenes normally except the IRL scene which can only last for 3 seconds. When noalbs is turned off, it can manually switch to various scenes normally. The following is part of my config
 },
  "switcher": {
    "bitrateSwitcherEnabled": true,
    "onlySwitchWhenStreaming": false,
    "instantlySwitchOnRecover": true,
    "autoSwitchNotification": true,
    "retryAttempts": 10,
    "triggers": {
      "low": 500,
      "rtt": 1500,
      "offline": 500
    },
    "switchingScenes": {
      "normal": "IRL",
      "low": "CLIP",
      "offline": "BRB"
    },
    thanks alot

**Comment by sungithub777** [comment]
I saw the value at http://localhost/stat
When I enable noalbs the output is 0kb/s and switches to brb
When noalbs is turned off, the output is 6000kb/s. I would like to know where I can find the bug so that it can operate according to my above settings. If the output is above 500kb, it will be switched to IRL. If it is lower than 500kb or there is too much delay, it will be switched to BRB.

**Comment by b3ck** [comment]
So you're saying that having NOALBS enabled changes your bitrate on your ingest server?  Could you explain your current setup so I can better understand?

**Comment by sungithub777** [comment]
1. You are right. When I do not enable noalbs, the value I see on ngnix is ​​4000kb/s. When I enable it, it will automatically become 0kb/s.
![no noalbs](https://github.com/user-attachments/assets/65483b66-5503-4a34-9556-b68b5c7c08da)
![noalbs](https://github.com/user-attachments/assets/defa2cdc-2bd2-4686-bcc0-01ff2cb6003b)

2.I would like to ask what information I need to give you. My streaming can be broadcast normally before using noalbs, but it automatically cannot detect the signal and switch the screen. I use the ddns function of noip and ngnix to set it up on my computer. If I need other information, I can reply Thank you my english not so good sorry bro

**Comment by b3ck** [comment]
LOL I'm even more confused.. um.. what NOALBS Version are you using, OBS Studio Version? What source are you using to show your ingest in OBS? Windows? Mac? Linux? for running NOALBS?

**Comment by sungithub777** [comment]
1.noalbs v2.11.2 obs v30.2.3
![noalbsv (2)](https://github.com/user-attachments/assets/087da2d8-0d6a-444e-aaca-58f683fb4f3a)


![obs version](https://github.com/user-attachments/assets/6f9803f8-c466-4e8a-a623-2ed4527bf6d0)
 
2. i use vlc source
![obs vlc](https://github.com/user-attachments/assets/aef5d8e8-f51b-45b8-add0-c3575f9cc1e6)

3.all use windows

maybe i need to paste my noalbs config? or ?

**Comment by b3ck** [comment]
DM me on Discord @ [b3ck](https://discord.com/users/96991451006660608)

**Comment by b3ck** [comment]
fixed, had wrong settings in streamServer.
