### ISSUE TITLE
https://twitchapps.com/tmi NOT WORKING

### ISSUE THREAD

**Issue by BONIOTTV** [715209/nginx-obs-automatic-low-bitrate-switching#180]
Hello guys, https://twitchapps.com/tmi is not working in my browser. 
Someone know why?

![image](https://github.com/user-attachments/assets/e2784e95-e9cd-438f-b5e9-8b95a496f6c7)

**Comment by BONIOTTV** [comment]
or how I can check my TWITCH_BOT_OAUTH=oauth: ????

**Comment by 715209** [comment]
Hi @BONIOTTV , 

B3ck made an alternative website to generate the OAuth token: https://b3ck.com/twitch/oauth
