### ISSUE TITLE
Feature Request: add a command to verify OBS connection

### ISSUE THREAD

**Issue by reedog117** [715209/nginx-obs-automatic-low-bitrate-switching#181]
As the title says. Basically something to verify OBS is up and potentially provide cpu/mem/hard drive stats.

**Comment by 715209** [comment]
Hi @reedog117, 

You can use the `!serverinfo`, which shows network and encoding information, but that currently only shows the stats when streaming from OBS. I can add the other stats to this command and a message in cases where OBS is active but not streaming.

**Comment by 715209** [comment]
I've removed the guard that checks if a stream is active, as the information from OBS is always available.
