### ISSUE TITLE
no error message but black rtmp video stream

### ISSUE THREAD

**Issue by Benjo1990** [715209/nginx-obs-automatic-low-bitrate-switching#20]
Hi i do all like the manual but when i stream to nginx server and from nginx server to obs studio i get only a black screen.
The system switch automaticly the scene, thats function also the system detect a video rate, but i dont get the video. ^^

**Comment by b3ck** [comment]
Did you install VLC? Are you using the VLC Media Plugin in OBS? If so what address are you using to pull in the video feed?

**Comment by Benjo1990** [comment]
Yes its installed, i use this link with the vlc plugin: rtmp://localhost:8080/publish/live

**Comment by b3ck** [comment]
So you changed the rtmp port to 8080 in the nginx.conf ??

**Comment by Benjo1990** [comment]
yes thats the config

![grafik](https://user-images.githubusercontent.com/60631372/73744285-c8339180-4750-11ea-83cd-7d5a1e27ae85.png)

**Comment by Benjo1990** [comment]
thats the NOALBS config:
![grafik](https://user-images.githubusercontent.com/60631372/73744749-b8687d00-4751-11ea-90a8-bc9a430300e1.png)

**Comment by Benjo1990** [comment]
here the OBS Studio RTMP screenshot:
![grafik](https://user-images.githubusercontent.com/60631372/73744877-02516300-4752-11ea-830c-668c26d390d5.png)

**Comment by 715209** [comment]
Hello Benjo,

You should use `rtmp://localhost/publish/live` in VLC.

**Comment by Benjo1990** [comment]
-.- that was the problem....   thanks <3

**Comment by b3ck** [comment]
Hey I was on my way to helping him, thanks for stealing my thunder brah 😕 ... 🤣👍
