### ISSUE TITLE
Error Fetching Stats & Can't stream to NGINX Server

### ISSUE THREAD

**Issue by specialprograms** [715209/nginx-obs-automatic-low-bitrate-switching#22]
Thanks for creating this awesome piece of software! I'm having two issues with NOALBS:

1) I cannot stream my phone to my NGINX server - I seem to have NGINX set up properly. I can see the stats page, along with the NGINX splash page in the browser. The logs do not show any errors and the program seems to be running correctly. However, when trying to connect my phone to rtmp://myiphere:port/publish/live, my camera cannot connect to it.

2) When running NOALBS, I get the error "[NGINX] Error fetching stats" - I suppose this is related to number 1, however, I can see my stats page and the NGINX splash page, so all of it looks like it should be running fine. 

Some info on this computer: It's an intel compute stick, gen 1 (intel atom processor) that I'm intending to use as an IRL streaming device. I'm not sure if NGINX can be run on this kind of hardware or not. Attached are my config.json for NOALBS and my nginx config. Thanks!

CONFIG.JSON
[config json.txt](https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/files/4333704/config.json.txt)

NGINX.CONF
[nginx conf.txt](https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/files/4333705/nginx.conf.txt)

**Comment by specialprograms** [comment]
Okay, I can now stream to my nginx server by replacing the last rtmp code bock in the NGINX.conf with this piece of code:

rtmp {
        server {
                listen 1935;
                chunk_size 4096;

                application live {
                        live on;
                        record off;
                }
        }
}

If I use the RTMP code block in the nginx.conf provided with NOALBS, I cannot stream to my nginx server. However, now that the rtmp code is altered, NOALBS just hangs after it connects to OBS. I no longer see the "[NGINX] Error fetching stats" message. Instead, nothing shows up at all. I can turn off my camera mid-stream but NOALBS doesn't force it over to the BRB screen. It just sits there and doesn't do anything.

So I'm assuming something is going wrong with that rtmp block of code in my nginx.conf that I posted in the previous message. Any help or guidance is much appreciated!

**Comment by b3ck** [comment]
add me on discord: b3ck#3517

**Comment by b3ck** [comment]
Also make sure all of your ports are being forwarded correctly, please see [this video](https://www.youtube.com/watch?v=rglDAIm73cM) in readme for further instructions.
