### ISSUE TITLE
Multiple Normal, BRB and LOW Scenes.

### ISSUE THREAD

**Issue by b3ck** [715209/nginx-obs-automatic-low-bitrate-switching#3]
It would be cool if we had an addition layer of Normal, BRB and LOW Scenes, that would back on each other, like for example I'm streaming to NormalScene2, from NormalScene2 it can only go to offlineScene2 or lowbitrateScene2, and vice versa if I am on NormalScene it will only use offlineScene and lowbitrateScene2. this would help up in really only my case, I don't see anyone else using this.  But it would be a neat option.

Kind Regards,
-b3ck

**Comment by b3ck** [comment]
Never mind, we figured out a work around.

**Comment by h1rule** [comment]
How did you fixed it?

**Comment by 715209** [comment]
He just runs the it twice
