### ISSUE TITLE
Is it possible to send a chat message in the same code block that detects instability?

### ISSUE THREAD

**Issue by darthclide** [715209/nginx-obs-automatic-low-bitrate-switching#32]
I would like to modify the code block that activates the "low bitrate" or "RIP" scenes to send a message in Twitch chat letting me know.

I want to avoid adding a timer for checking the !bitrate response since you already have optimized the code to detect these events elsewhere. But if it is impossible to interact with IRC in that code block, could you tell me where the commands are created so I can do this brute force method?

**Comment by b3ck** [comment]
If you type "!notify on" in twitch chat after NOALBS is running it will notify in twitch chat of the scene changes.  This should be enabled by default. Unless you turned it off in the config file.

**Comment by darthclide** [comment]
Hmmm, I assume this will only trigger when the stream actually starts? I was manually clicking the scenes to see if it would trigger a chat message and nothing happened. This made me wonder if this "notify" was simply a popup on the computer, not a message in chat.

**Comment by b3ck** [comment]
Having the "notify on" will announce in twitch chat when a scene changes due to the following reasons: low bitrate, loss of source, regain of source, or when you switch a scene from the chat manually, ex; !ss LIVE or !ss PRIVACY etc..

**Comment by darthclide** [comment]
I do not see this !ss command in the description, but when you say "loss of source" you mean if the connection goes completely dead right? And can you confirm this is tied up in the code checking bitrate and that the reason my tests offline showed no messages in chat is because I am not streaming?

**Comment by b3ck** [comment]
I'm sorry the !ss command is a alias I added for !switch (see screenshot below).
![Screenshot_20200628-082958_Chrome](https://user-images.githubusercontent.com/1740542/85949032-e5444900-b919-11ea-828d-9e084f932978.jpg)


Correct, and yes it was because you were not streaming, you can enable it to "operate" when not streaming in the config; (see screenshot below)
![Screenshot_20200628-083352_Chrome](https://user-images.githubusercontent.com/1740542/85949074-2dfc0200-b91a-11ea-94c0-b9ce53194d65.jpg)

Just change it false, start/restart NOALBS and it will run as if you were streaming.

**Comment by darthclide** [comment]
I meant I tested it while streaming to the RTMP server. No chat messages came in. enableAutoSwitchNotification is set to true.

**Comment by b3ck** [comment]
The option in the config is for when OBS is streaming, if set to true it will only "operate" when streaming in OBS to twitch. If set to false it will do it whenever.

**Comment by darthclide** [comment]
So I have it set to false. Why are there no Twitch chat messages coming through when the scene switches?

**Comment by 715209** [comment]
You will only see twitch chat messages when you are streaming from OBS and not manually switching scenes.

**Comment by b3ck** [comment]
Manually meaning switching the scenes inside OBS vs in chat using the !switch command.

**Comment by darthclide** [comment]
Ah okay. I was getting conflicted on what you meant, and I just did a test stream to Twitch from my computer, and it is correctly putting messages into chat like I want. Maybe you could change it in a future update? Because if you are in the same config file and you tell it "yes, I want auto switching to work even without streaming" at the same time as "yes, I want Twitch chat notifications", you would assume these chat messages will work even without sending any data to Twitch ingest servers.

Perhaps at the same time you do this, you could include a way for us to modify what the message response is? Thanks for the help!

**Comment by 715209** [comment]
This was done to not send messages in chat after you stopped streaming or when you are just changing things in OBS. 

Also you can already change the message here:
https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/blob/86ac29d04895e43151d5bc8c4ad4ebdca0564beb/locales/en.json#L11

**Comment by darthclide** [comment]
Ah, so here is the output. May I ask where the logic is so I can create my own commands as well?

**Comment by 715209** [comment]
You can create your own commands in `rc/components/Chat.js`

**Comment by darthclide** [comment]
Thank you! I didn't think to check the src because I assumed this was a "do not touch" folder.

**Comment by b3ck** [comment]
Always explore the source, you never know what you'll find or learn 😁👍
