### ISSUE TITLE
Auto Detect Host/Raid

### ISSUE THREAD

**Issue by Clemens22497** [715209/nginx-obs-automatic-low-bitrate-switching#33]
For some time, hosts and raids have no longer been recognized and the stream has no longer ended automatically.

**Comment by 715209** [comment]
Do you have the option enabled in the config?

https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/blob/86ac29d04895e43151d5bc8c4ad4ebdca0564beb/config.json#L31

**Comment by Clemens22497** [comment]
Thanks for the reply. Yes the option is on. We have already switched this on and off in the config as well as via chat command for testing.

**Comment by 715209** [comment]
It seems to be working fine for others. Have you tried a clean install?

**Comment by Adraenyse** [comment]
@Clemens22497 Is your OAuth token for the chatbot account current/valid, and does the chatbot account have the Editor role enabled?

**Comment by Clemens22497** [comment]
Hi, it suddenly worked again without reinstalling and restarting the server, so I have no idea what it was all about. Maybe he choked briefly.
