### ISSUE TITLE
How to set up highRttTrigger?

### ISSUE THREAD

**Issue by UnisonRU** [715209/nginx-obs-automatic-low-bitrate-switching#38]
How to set up highRttTrigger?

I get rtt in the following format: "rtt":0.031

I watch him from the link during the broadcast: http://127.0.0.1:8082/manage/srt_receiver_stats
I also have such a link: http://127.0.0.1:8082/manage/rtmp_status

**Comment by UnisonRU** [comment]
I get the error just as often:

[11.08.2020] [20:31:16] [OBS] » ×  error     [NIMBLE] Error fetching stats: TypeError: Cannot read property 'state' of undefined

**Comment by UnisonRU** [comment]
I was informed that NOALBS does not have a check for "state". The program immediately tries to get the data.

An example of statistics:
{"SrtReceivers":[{"id":"0.0.0.0:9000","state":"disconnected"}]}

or

{"SrtReceivers":[{"id":"0.0.0.0:9000","state":"disconnected","retryCount":1}]}

or

{"SrtReceivers":[{"id":"0.0.0.0:9000","state":"connected","retryCount":1,"stats":{"time":5685,"window":{"flow":8192,"congestion":8192,"flight":0},"link":{"rtt":0.032,"mbpsBandwidth":1441.96,"mbpsMaxBandwidth":1000},"recv":{"packetsReceived":1836,"packetsLost":0,"packetsDropped":0,"packetsBelated":0,"NAKsSent":0,"bytesReceived":2496960,"bytesLost":0,"bytesDropped":0,"mbpsRate":3.51345}}}]}

**Comment by UnisonRU** [comment]
@715209 can you fix this please?

**Comment by b3ck** [comment]
Try using the new SRT method with SLS, it's much easier than using nimble, all you need is WSL or a Linux Environment.

Check it out here: https://gitlab.com/mattwb65/srt-live-server


Kind Regards,
-b3ck

**Comment by 715209** [comment]
Hey @UnisonRU

**Comment by 715209** [comment]
Hey UnisonRU,

I've seen this issue happen before, you most likely used the wrong port in the "id" field.
