### ISSUE TITLE
Chat info when scenes are switching?

### ISSUE THREAD

**Issue by capsload2** [715209/nginx-obs-automatic-low-bitrate-switching#39]
Is there any way i can get a chat message once the scene is switching?

**Comment by 715209** [comment]
Hello capsload2, 

This should be enabled by default or you can enable it by using the `!notify on` command.

**Comment by capsload2** [comment]
Thanks! Will try it out.

**Comment by 715209** [comment]
It's set to only work when you are streaming from OBS.
