### ISSUE TITLE
I have set this up 3 times off the Video and wont work.

### ISSUE THREAD

**Issue by deuceNICKalo** [715209/nginx-obs-automatic-low-bitrate-switching#42]
I live stream IRL Saltwater fishing streams and this obs low bitrate switching would help me a ton but no matter what I do even after 3 uninstalls and start overs, I just keep getting x Error [NGINX] Error Fetching Stat.  Please help.  I followed the video exactly and my port forwarding shows the ports being open so I am lost.  Thanks and here is my Nginx config file, its just like the video.

 "obs": {
        "ip": "localhost:4444",
        "password": "mypassword",
        "normalScene": "LIVE",
        "offlineScene": "BRB",
        "lowBitrateScene": "LOW",
        "refreshScene": "REFRESH",
        "lowBitrateTrigger": 800,
        "highRttTrigger": 2500,
        "refreshSceneInterval": 3000,
        "requestMs": 2000,
        "onlySwitchWhenStreaming": false
    },
    "rtmp": {
        "server": "nginx",
        "stats": "http://localhost/stat",
        "application": "publish",
        "key": "live"
    },
    "twitchChat": {
        "channel": "deucenickalo",
        "botUsername": "deucebot7",
        "oauth": "myoauth",
        "enable": true,
        "prefix": "!",
        "enablePublicCommands": true,
        "publicCommands": ["bitrate"],
        "enableModCommands": true,
        "modCommands": ["refresh", "fix", "trigger", "sourceinfo", "obsinfo"],
        "enableAutoSwitchNotification": true,
        "enableAutoStopStreamOnHostOrRaid": true,
        "adminUsers": ["deucenickalo", "deucebot7", "doctordilbuck", "marbear__"],
        "alias": [["r", "refresh"], ["f", "fix"], ["b", "bitrate"]]
    },
    "language": "en"
}

**Comment by b3ck** [comment]
This is the NOALBS config file, did you even start the NGINX-RTMP server?

**Comment by deuceNICKalo** [comment]
I did launch NGINX before as it showed in my Task Manager as running.  I also check port 80 to see if anything else was occupying it but it shows NGINX is the only thing using it and that port 80 is listening.  This is the first time I have ever done anything like this so I tried to make sure to follow everything to the letter with the setup video.  I don't know if this makes a difference but I use Prism Studio Live on IOS to mobile stream.  I tried it as well with Streamlabs App and that gave me same error.

**Comment by 715209** [comment]
Hello!

Do you see the livestream when you watch it through VLC or media source?

**Comment by deuceNICKalo** [comment]
No.  So I added the VLC source and added my ip to Prism streaming app but when I go live, prism acts like I’m live but nothing shows up on OBS and NOALBS gives me the error of “NGINX error fetching stats.”  The OBS pluggins seem to work cause with NOALBS and OBS running, if I try to switch to LIVE it kicks me to the BRB scene cause it can’t detect bitrate.  But as soon as I go live it gives me that “Error fetching stats” and no video.

**Comment by b3ck** [comment]
Did you make sure you opened the firewall ports and aslo forwarded the ports on your router? Like 100% sure? If you are and it still doesn't work, then message me on discord @ b3ck#3517

**Comment by deuceNICKalo** [comment]
I went through my router and setup the port forwarding for 1935 and 4444 and set them to both.  I then went to check my ports and put in my local ip and both 1935 and 4444 said they were open.  The windows firewall confuses me a little as I went into it and set port 80 to be open but when I go same port check site it says port 80 is closed.  Now like I said I am new to this so I don’t know if it should say open like 1935 and 4444 or not.  I went into cmd and typed in netstat - aon to find port 80 and see what was on it and it says that NGNIX is so outside of that I am not sure.  I know every router is different and my ARRIS router def had different look to its port forwarding setup but I YouTube my specific model and how to do it and I’m pretty sure I did it right.  How would I check something like that if it was wrong?

**Comment by deuceNICKalo** [comment]
I appreciate you taking the time to help me with this.  I run my channel super early cause of what I do with Saltwater Fishing so my day starts around 3 am so gonna have to head to bed.  I will follow up tomorrow afternoon when I get off the water and I will go ahead and message you in discord and when you are not busy and it is not an inconvenience for you maybe I can try a few different things you recommend.  Thank you very much for your time and help and look forward to speaking more tomorrow.

**Comment by b3ck** [comment]
Sounds good, looking forward to the update.

**Comment by deuceNICKalo** [comment]
Sorry for the delay, had a water emergency today so things kind of got messed up.  Still would love to get this working but just don't have the time to work on it tonight.  If you are still available maybe tomorrow I will send you a message and we can go from there but I don't want to take up your time if you cant.  Thanks again and will contact you tomorrow.

**Comment by b3ck** [comment]
Are you still having issues with this deuce?

**Comment by deuceNICKalo** [comment]
I haven't really used it in a little while cause there were some major
audio lag issues that started that weren't an issue before and then the
chat spam when it is stuck switching scenes for low bit rate.  I have just
been super busy lately so that has been an issue too but plan to try to and
get back to using it I hope.
