### ISSUE TITLE
Getting Stats of multiple Streams for NOALBS

### ISSUE THREAD

**Issue by Chucks1860** [715209/nginx-obs-automatic-low-bitrate-switching#47]
Hey there,

first of all I need to say that I'm totally new to this and don't have any coding experience but always like to learn new things.

I've set up the nginx server following the instructions and succeeded in adding more rtmp streams (via application name in the nginx config).
Though they need quite a while to show up in OBS when starting to stream to one of them it works somehow (still have to figure out why it might take up to 2 minutes until the stream is visible within the OBS source).
My problem is that I can't figure out how to set up the config.json file to get the stats of at least 2 rtmp Streams at the same time so that the automatic scene switcher would only change scenes, when BOTH streams have issues (or one is offline and the other one has low bitrate problems or a disconnect).

The main goal would be that 2 Streamers can stream to the same Twitch channel and hand off the stream from one to another without having to end the stream and start a new one (wich would already be possible if there is no automatic scene switching involved) BUT aditionally with an automatic scene switcher that changes to a LOW BITRATE or BRB Scene when not at least one of those streams is stable.

Example:
Streamer A is streaming and ends his stream for Streamer B to take over.
NOALBS would only react to Stream A (at default json config) and would switch to BRB when Stream A goes offline even though Stream B is online at that moment (because NOALBS is only set to "listen" to Stream A).

The default json Code is:
`    "rtmp": {
        "server": "nginx",
        "stats": "http://localhost/stat",
        "application": "publish",
        "key": "live"
    },`

I tried to add more applications so it looked something like this:
`    "rtmp": {
        "server": "nginx",
        "stats": "http://localhost/stat",
        "application": "publish",
        "key": "live"
        "application": "StreamA",
        "key": "live"
        "application": "StreamB",
        "key": "live"
        "application": "StreamCMobile",
        "key": "live"
    },`

I might be totally wrong here but (without any coding experience) this listing seemed to make sense to me... ;-)
Well, as you can guess, it might have seemed to make sense to me but not for NOALBS! :-D
At least under http://localhost/stat it does indeed show me all of the Streams' info and I can connect using the different application names.

How do I need to change the config.json to achieve the described goal?
Ist it even possible with multiple streams?
Or do I have to find a different solution?
Do you need more or other info?

Thanks in advance!

**Comment by b3ck** [comment]
NOALBS doesn't currently have multi-stream monitoring, it has been brought up before and 715209 plans to add it in a future release, just no ETA on it though.

**Comment by 715209** [comment]
Hi! This has been possible since NOALBS v2.
