### ISSUE TITLE
No bitrate Amazon AWS

### ISSUE THREAD

**Issue by Vayren7** [715209/nginx-obs-automatic-low-bitrate-switching#48]
Hi there
I have bitrate problems, I use Amazon AWS and wanted to incorporate the auto switcher.
The problem is that the bitrate is not detected.
I have followed this tutorial: [https://www.youtube.com/watch?v=_GTOb8lmOB8](url)
Maybe i have to download all in the AWS server idk.
I appreciate your help.

**Comment by b3ck** [comment]
Figure it out? What was the issue?
