### ISSUE TITLE
Streaming computer won't restart streaming unless OBS restarted

### ISSUE THREAD

**Issue by msoultan** [715209/nginx-obs-automatic-low-bitrate-switching#49]
I have a weird one - I have nginx installed on our streaming server and everything works great - I can send rtmp feeds from OBS to the server, start/stop OBS streaming over and over without any issue.  My nginx.conf rtmp section is pretty generic:

```
rtmp {
	server {
		listen 1935;
		chunk_size 4096;

		application remote1 {
			live on;
			}
		}
	}
```
Then I set up NOALBS (disabling my nginx server in favor of the one provided) and for the most part, everything worked... kinda.  When I try and stop/start the stream on my streaming OBS computer, it will stop, but when I try and start it again, it won't let me connect.  The only way I can reconnect is by closing OBS and reopening it and then it will let me start streaming again.  However, if I hit stop/start, it won't work and I have to close out OBS.  I even tried restarting nginx to see if that was holding something up, and it didn't make a difference - the only way to get it working was to restart OBS on my streaming machine.

So, to test things out, I removed all of the rtmp stuff from the NOALBS-provided nginx.conf to about match mine and that made it work, so there's some rtmp directive in there that is causing OBS on my streaming computer to get hung up - any ideas what that might be?  Btw, this is what the rtmp portion looks like in my nginx.conf (should be identical to what's on the github repo):

```
rtmp {
    log_format compression '';

    server {
        listen 1935;
        ping 30s;
        notify_method get;
        chunk_size 8192;
        ack_window 8192;
		sync 4ms;
		interleave on;
        access_log logs/rtmp-access.log compression;

        # Stream to "rtmp://IPHERE/publish/live".
        application publish {
            live on;
			wait_video on;
            wait_key on;
            exec_options on;
            publish_notify on;
            play_restart on;
            drop_idle_publisher 4s;
            idle_streams off;
			sync 4ms;
			interleave on;
        }
    }
}

Thanks!
Mike

**Comment by b3ck** [comment]
I believe that is an new thing with OBS v26, I don't quite know exactly why it hangs but I am aware that OBS devs are are aware and are actively trying to patch it.

**Comment by DigibitDK** [comment]
@msoultan
I found the fix for that some time ago. It not really a new thing. Change 'ack_window' to 16384 :)

/Michael

**Comment by msoultan** [comment]
Ok, I figured out what was causing this - it relates specifically to this setting:

ack_window 8192;

If I remove that setting and let it revert to its default (5000000) then I am able to stop/start the remote OBS without issue.  Here's the docs on that directive:

https://github.com/arut/nginx-rtmp-module/wiki/Directives#ack_window

Can I use the default or did you pick that for a specific reason for NOALBS to function correctly?

**Comment by b3ck** [comment]
I was mainly matching what I used back in the day when I was using Bitstream, the app itself had an ack window of 8192, seemed to work well.

When using RTMP I just use the built-in Node-Media-Server rather than NGINX, it seems to have less issues.

I also use the new Media Source in OBS vs the VLC Source.

**Comment by msoultan** [comment]
So we tested the NMS server and while it works well, as far as I can tell it only supports one source... can it support more?  Is there a way to send 3 RTMP sources (gopro, drone, and phone) to the NMS server and have NOALBS monitor the gopro feed?

And yes, I remember you mentioning the use of the new Media Source settings in OBS - on our same server we also host multiple DJs (for non-IRL events) so that's why we're still using Nginx and using the ack_window of 8129 holds up the source source DJ's OBS from shutting down - there is no Media Source issue at play in this scenario.  We wanted to use the NMS server, but ran into the issue above (more than one source).

Now in regards to the Media Source vs VLC source (in regards to load latency), we did try it and it loads fast, but it also doesn't have an easy way of restarting the feed should it get funky (which happens quite a bit when we're hosting other DJs).  This is where using the VLC source restart button is helpful.  We also found the need to keep the source alive (whether it's visible or not) otherwise it just keeps getting restarted and causes more hassles than it's worth (as far as what we found...).

**Comment by b3ck** [comment]
yes you can have as many source as you want with NMS, the New Media Source has a reconnect option, here is how I have mine setup:

![image](https://user-images.githubusercontent.com/1740542/109899503-9777a180-7c5b-11eb-9a94-6198de210b0c.png)

With these settings I have no issues while streaming RTMP.

I guess I don't quite understand your work flow here.. do you have time for a Discord Voice Call?

b3ck#3517

**Comment by DigibitDK** [comment]
msoultan >
 
> ack_window 8192;
> 
> If I remove that setting and let it revert to its default (5000000) then I am able to stop/start the remote OBS without issue. Here's the docs on that directive:

If you use default ack_window, !fix wont work well.

**Comment by b3ck** [comment]
I've never had to use fox when using the Media Source.

**Comment by DigibitDK** [comment]
Correct. 'Media Source' kind of leaves !fix and !refresh in depreciation.
