### ISSUE TITLE
Can NOALBS work with any nginx install

### ISSUE THREAD

**Issue by msoultan** [715209/nginx-obs-automatic-low-bitrate-switching#50]
I noticed that NOALBS includes the gryphon nginx distro with the rtmp module compiled into it, but I was curious if NOALBS will work with other distros.  The reason I ask is because I found a newer version of nginx with the rtmp module:

https://github.com/ustoopia/nginx-rtmp-1.17.10-windows-php-videojs-dashjs

so I figured I'd use that one as I believe 1.7 (which is in gryphon) is about 7 years old.  What didn't know is if NOALBS is just monitoring nginx or if it's actually compiled into the gryphon release packaged with NOALBS.

Thanks!
Mike

**Comment by b3ck** [comment]
Yes just as long as it outputs a stats page in the same format as the 1.7 one in NOALBS, you could also try using the built-in NMS, then you don't need any nginx at all.

**Comment by msoultan** [comment]
So I figured I'd give NMS a try and you actually just solved a problem we've been going nuts over - first, whenever we'd connect OBS to our nginx rtmp server, it would take a while for the feed to show up on OBS running on that server as an input source - with NMS, it starts up near instantly!  Also, we were having issues with nginx where it would sometimes give us a grey screen instead of the feed, and sometimes it would just fail such that we'd have to stop the source OBS and then restart the feed on the server OBS as well - with this setup, it loads/unloads the feed much more effortlessly.  Cool - I'm definitely gonna play with this some more :)

Thanks!!
Mike

**Comment by b3ck** [comment]
Also use Media source instead of VLC Source, change the the settings to this: 
![Screenshot_20210209-040142_TeamViewer](https://user-images.githubusercontent.com/1740542/107347614-9e135e80-6a8b-11eb-82cd-a0d60cd05b4a.jpg)

**Comment by msoultan** [comment]
Ok, so is that a recent change?  I could swear this wasn't there before, but I could very well be mistaken.  It seemed like all the documentation/posts were recommending to install VLC and then use a VLC media source for rtmp sources.

Btw, this NMS server - is this essentially the same thing as Nginx with rtmp?  In other words, is this a production-quality rtmp server?  I've never worked with node.js stuff before and all the guilds recommend using Nginx so that's what we used... but I'm open to try new stuff :)

Thanks so much for your help!  This NOALBS tool is realy cool!

**Comment by b3ck** [comment]
Yeah I believe it changed starting v26, Node-Media-Server is very production ready and can be used and relied on professionally, my tutorial video says to use VLC and VLC source etc.. as the Media Source wasn't as reliable.  But now it is by far the best way to go.

**Comment by msoultan** [comment]
Very cool!  Ok, well, I guess I'll be doing some more reading on NMS.  Thanks!!

**Comment by msoultan** [comment]
So is there any documentation anywhere on what directives can be used in config.json?  What I'd like to do is set up multiple applications, some for ingest into our server, and some to push to multiple locations (i.e. push to two different Twitch accounts).  I looked everywhere but I can't seem to figoure out the correct syntax to accomplish this.  This what I use for Nginx:
```
rtmp {
	server {
		listen 1935;
		chunk_size 4096;

		# Input ingest that feeds into OBS
		# --------------------------
		application live {
			live on;
			}
		
		# Splitter ingest that comes from OBS
		# --------------------------------
		application splitter {
			live on;
			push rtmp://live-sfo.twitch.tv/app/[stream key1];
			push rtmp://live-sfo.twitch.tv/app/[stream key2];
			}
		}
	}
```

**Comment by b3ck** [comment]
That doesn't go in the `config.json` for noalbs, that goes in the nginx `nginx.conf` file.

Try following this: [RTMP Multistreaming](https://www.scaleway.com/en/docs/setup-rtmp-streaming-server/#-Setting-up-Multistreaming)

Let me know how it goes.

**Comment by msoultan** [comment]
Sorry - my message was so unclear it's horrible!!  Lemme try this again:

What would be the comparible directives that I would use for NMS to achive the same results as the nginx.conf example I have in my previous message.

**Comment by b3ck** [comment]
Working on it, give me a bit.

**Comment by b3ck** [comment]
Okay so NMS makes this a bit tricky, because the relay directive just adds the key you're streaming to, to the end of the rtmp url for the relay, example config:

```
    "rtmp": {
        "application": "live",
        "key": "cam1"
    },
    "nodeMediaServer": {
        "rtmp": {
            "port": 20000,
            "chunk_size": 60000,
            "gop_cache": true,
            "ping": 30,
            "ping_timeout": 60
        },
        "http": {
            "port": 8000,
            "mediaroot": "./html",
            "allow_origin": "*"
        },
        "relay": {
            "ffmpeg": "C:/ffmpeg/bin/ffmpeg.exe",
            "tasks": [
                {
                    "app": "live",
                    "mode": "push",
                    "edge": "rtmp://ord02.contribute.live-video.net/app/example_stream_key"
                }
            ]
        }
    },
```

And I stream to /live/cam1, it tries to push the relay to `rtmp://ord02.contribute.live-video.net/app/example_stream_key/cam1`

the only way I can get around this is to use `example_stream_key` as my key, so I was able to get it to work like this:

```
    "rtmp": {
        "application": "live",
        "key": "example_stream_key"
    },
    "nodeMediaServer": {
        "rtmp": {
            "port": 20000,
            "chunk_size": 60000,
            "gop_cache": true,
            "ping": 30,
            "ping_timeout": 60
        },
        "http": {
            "port": 8000,
            "mediaroot": "./html",
            "allow_origin": "*"
        },
        "relay": {
            "ffmpeg": "C:/ffmpeg/bin/ffmpeg.exe",
            "tasks": [
                {
                    "app": "live",
                    "mode": "push",
                    "edge": "rtmp://ord02.contribute.live-video.net/app"
                }
            ]
        }
    },
```

then whatever I was using to stream via RTMP I would stream to `/live/example_stream_key` and then it would stream to twitch and I would use that `example_stream_key` in OBS as well to pull in the video feed as a source in a scene.

I am sure there is a way around this and I'm looking at the code now to see if there is a work around or maybe I just missed something.. either way here is a solution.. a shitty solution.. but still a solution =/

**Comment by msoultan** [comment]
That is a weird quirk!  I'll have to play with it tomorrow when I get a free moment to get a better feel for the behavior.  Is there a list of all the various directives and associated options (i.e. relay, rtmp, nodeMediaServer, etc), or are you just digging through the code?  I do a decent amount of programming with Python, but I haven't done anything with node so I'm not really sure where to even look... I might have to start playing with it.

So I posted a somewhat simple example - my ultimate goal is to have multiple ingest options so that multiple DJs can connect into my rtmp server using different rtmp ingests (i.e. rtmp://server/live/dj1, rtmp://server/live/dj2, rtmp://server/live/dj3, etc) so that will get interesting as the Twitch ingest keys are entirely different than the inbound feeds (were this limitation prove to be the only way to accomplish this).

If it helps, I'm happy to post something to the NMS github as well as this is kinda unrelated to NOALBS, but I'm super-appreciative for your help!!

**Comment by b3ck** [comment]
> If it helps, I'm happy to post something to the NMS github as well as this is kinda unrelated to NOALBS

Go for it, I'll keep an eye out for it.

And no problem.. I was super curious on if NMS had the ability to do this as well =)

I was looking through this: https://www.nodemedia.cn/doc/web/#/5?page_id=11

And this: https://hub.docker.com/r/illuspas/node-media-server
