### ISSUE TITLE
Add all mods as admins?

### ISSUE THREAD

**Issue by DigibitDK** [715209/nginx-obs-automatic-low-bitrate-switching#51]
Is it possible, to type a string in the config-file, that will give all mods status as admins? Or what can I change in the Noalbs-files to achieve that?

Now I manually add mods to admins, but Ill have to keep track on it, when new mods is added to Twitch, or some is removed.

(PS: I have made a Danish-language-file for your program, if you would like to add that) 

Best regards
Michael.

**Comment by 715209** [comment]
Hello MIchael,

It is currently not possible to do this and I don't think it's a good idea to give mods access to all commands.
Instead you could just add the commands you want the mods to have access to here:
https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/blob/3c3c8101780c5f3baa3dbd516a258f560b684c5c/config.json#L30

**Comment by DigibitDK** [comment]
Of course, seems like a good solution - Thanks :)

**Comment by 715209** [comment]
Oh also you can open a PR for the language file or attach it here and i will add it, thanks!
