### ISSUE TITLE
The word 'is' is not a part of locale language files.

### ISSUE THREAD

**Issue by DigibitDK** [715209/nginx-obs-automatic-low-bitrate-switching#52]
Referring to the language-files, some reply's contains the word 'is'.  But 'is' are not to be found in the locale language files.

This means, that 'is' will be a part of any language-file selected.

Eg.
!autostop =  Auto stop stream is disabled ('is' can't be changed, but should only be used in en.json)
!public = Public comands is enabled (Again 'is' - And you have a typo in this as well ... commands, not comands)

/Michael.

**Comment by 715209** [comment]
Hello Michael,

Looks like I forgot to remove the "is" part when checking the current status of the command.
I will remove that, thanks!

**Comment by DigibitDK** [comment]
U welcome :)
