### ISSUE TITLE
[NGINX] Error fetching stats

### ISSUE THREAD

**Issue by HyperVolcan** [715209/nginx-obs-automatic-low-bitrate-switching#55]
Hi all, I've configured everything in the guide RTMP stream to NGINX server working fine I can read the stats page. However when I end the RTMP connection on my phone to the server (Stop streaming) it does not switch to my offline scene it just sits there saying 
[NGINX] Error fetching stats
[NGINX] Error fetching stats
[NGINX] Error fetching stats 

Until I start the RTMP stream\connection again. 

Tried this on a windows setup and to external centos 8 setup same issue

**Comment by HyperVolcan** [comment]
I've switched to using Nimble instead which works fine thansk @b3ck

**Comment by 715209** [comment]
Hey HyperVolcan, 

Glad you got it working! 
Could i still get the version number you are using, so I can test if there's no bug with NGINX.

**Comment by HyperVolcan** [comment]
> Hey HyperVolcan,
> 
> Glad you got it working!
> Could i still get the version number you are using, so I can test if there's no bug with NGINX.

Hey it was latest version of noalbs and error I had was with the included NGINX version & also NGINX 1.18.0 on centos 8

**Comment by b3ck** [comment]
Ahh you weren't using the nginx-rtmp supplied with NOALBS, I wonder.. was
it still generating a stats page from statxsl and was it being called out
in the NGINX config?

**Comment by 715209** [comment]
I did break the switching on stop last week for a day so I was wondering if that was the issue.

**Comment by DigibitDK** [comment]
I have the same issue. Using NGINX. 1.9.1 works fine, 1.9.3 makes [NGINX] Error fetching stats

**Comment by 715209** [comment]
I'm using NGINX 1.19.6 and it's working fine.

**Comment by DigibitDK** [comment]
1.17.5 here. I might check up on that.

**Comment by HyperVolcan** [comment]
Hey @715209 mate looks like you fixed the code for stopped stream or null stream should I try NGINX again?

**Comment by b3ck** [comment]
You can if you want.. if NMS is working for you then why change it? NMS is
built-in.. that's one less thing to run..


*-b3ck*

**Comment by DigibitDK** [comment]
No, still [NGINX] Error fetching stats using v1.9.4 with latest version of NGINX. (Your v1.9.1 works fine)

NGINX: 1.19.7
RTMP: 1.2.1
FFMPEG: 4.3.1

/Michael.
