### ISSUE TITLE
Error fixing the stream

### ISSUE THREAD

**Issue by wudiam** [715209/nginx-obs-automatic-low-bitrate-switching#57]
When I try to !fix or !f it says "Trying to fix the stream" and then "Error fixing the stream". In the console which is on Linux VPS it says "xxx Executed fix command" and nothing else. I use the built-in nodeMediaServer.
I used to use Nginx RTMP server before and there was no such issue but it sometimes got quite laggy so I want to test this one out.

**Comment by b3ck** [comment]
Are you also using the built-in Media Source in OBS? As far as I know the !f command only works for NGINX-RTMP.

@715209 Can we get the !f command to work with the built-in NMS?

**Comment by wudiam** [comment]
Yes, I am also using Media Source in OBS. If you could make !f work for NMS in the future it would be awesome.

**Comment by b3ck** [comment]
If it's possible @715209 will let us know 😆👍

**Comment by 715209** [comment]
This has already been updated in the latest version of NOALBS. Update OBS and/or the OBS WebSocket.

**Comment by wudiam** [comment]
Okay updated OBS WebSocket and it seems to work... Goes blackscreen for a second and comes back but doesn't give confirmation of success in chat like it did with Nginx but that is not important as long as it actually fixes.
