### ISSUE TITLE
Save current bitrate into .txt file

### ISSUE THREAD

**Issue by condor125** [715209/nginx-obs-automatic-low-bitrate-switching#58]
I would like NOALBS to periodically save the current bitrate into a tex tfile so I can display it in OBS

**Comment by b3ck** [comment]
Have you tried this yet? https://github.com/b3ck/rtmp-bitrate-html

**Comment by condor125** [comment]
exactly what I was looking for, thanks!

**Comment by b3ck** [comment]
No problem, enjoy!
