### ISSUE TITLE
Noalbs does not announce automatic scene switching

### ISSUE THREAD

**Issue by glowfishDE** [715209/nginx-obs-automatic-low-bitrate-switching#59]
Hi,

while the actual noalbs build is switching scenes very well and it can post into chat:

22:40 secret: !bitrate
22:40 secret_Bot: Current bitrate: 6280 Kbps, RTT 48.921 ms

i do not get ANY automatic scene switching chat messages from it when it changes to the offline or BRB scene.

Here is my config:

{
    "obs": {
        "ip": "1.2.3.4:4444",
        "password": "1234",
        "normalScene": "Stream ACTIVE (Outdoor)",
        "offlineScene": "Stream ended / Good night (Outdoor)",
        "lowBitrateScene": "Stream paused / BRB (Outdoor)",
        "refreshScene": "Stream paused / BRB (Outdoor)",
        "lowBitrateTrigger": 1000,
        "highRttTrigger": 2500,
        "refreshSceneInterval": 10000,
        "requestMs": 2000,
        "onlySwitchWhenStreaming": false
    },
    "rtmp": {
         "server": "srt-live-server",
         "stats": "http://127.0.0.1:8181/stats",
         "publisher": "live/stream/belabox"
    },
    "twitchChat": {
        "channel": "secret",
        "botUsername": "secret_bot",
        "oauth": "oauth:secret",
        "enable": true,
        "prefix": "!",
        "enablePublicCommands": true,
        "publicCommands": ["bitrate"],
        "enableModCommands": true,
        "modCommands": ["refresh", "fix", "trigger", "sourceinfo", "obsinfo"],
        "enableAutoSwitchNotification": true,
        "enableAutoStopStreamOnHostOrRaid": true,
        "adminUsers": ["secret_bot", "secret", "topsecret"],
        "alias": [["r", "refresh"], ["f", "fix"], ["b", "bitrate"]]
    },
    "language": "en"
}

I would be more than thankful if you can point me into the right direction why i am not getting these (for me crucial) chat messages.

Thanks

**Comment by 715209** [comment]
Hello glowfishDE,

NOALBS only sends these messages when you're actually streaming from OBS.

**Comment by glowfishDE** [comment]
Ahh ok that might be the reason - i have not tested that yet. Thanks alot. I´ll close this issue :)
