### ISSUE TITLE
Add a second RTMP server

### ISSUE THREAD

**Issue by kashayar** [715209/nginx-obs-automatic-low-bitrate-switching#60]
Hey hey, 
first of all: GREAT PIECE OF SOFTWARE. THANK YOU SO MUCH!!!

Now I have a request, if possible: Is it possible to expand NOALBS to support a second RTMP channel? So if there is a signal on any of the two it will switch scenes to the matching one and if not go to BRB?

Thank you in advance,
Kashayar

**Comment by b3ck** [comment]
it's been talked about, most likely coming in v2.0

**Comment by kashayar** [comment]
That would be so great. Thank you for this great tool. Any release plan for 2.0?Am 08.03.2021 18:26 schrieb b3ck <notifications@github.com>:
it's been talked about, most likely coming in v2.0

**Comment by b3ck** [comment]
nope.
