### ISSUE TITLE
error     (node:7801) in NPM Console, but everything works?

### ISSUE THREAD

**Issue by irrKopf** [715209/nginx-obs-automatic-low-bitrate-switching#61]
Hey @all -  i have a problem... I have OBS installed on a Linux Ubuntu server. I left out the whole part with NGINX and got the media server running. The whole system works, but I got this error message in Termninal @ NPM Start after a video signal is arriving... But the system is normaly running... what is the issue?
I only configured the config.json

> [4/26/2021] [4:23:47 PM] [NMS] › ✖️  error     (node:7801) UnhandledPromiseRejectionWarning: #<Object>
[4/26/2021] [4:23:47 PM] [NMS] › ✖️  error     (node:7801) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[4/26/2021] [4:23:47 PM] [NMS] › ✖️  error     (node:7801) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 

I put the following Line in the config.json in between of the line 15 and 29

>    "rtmp": {
        "application": "publish",
        "key": "HERE IS MY STREAMING KEY XYZ"
    },
    "nodeMediaServer": {
        "rtmp": {
            "port": 1935,
            "chunk_size": 60000,
            "gop_cache": true,
            "ping": 30,
            "ping_timeout": 60
        },
        "http": {
            "port": 8000
        }
    },

The server works ... Live image arrives, scene switches to LIVE, when I finish it changes to BRB. 
But I would like to know the error in the console

**Comment by 715209** [comment]
Hey IrrKopf,

This error seems to be happening inside NMS. I'm not sure I can do anything about it.

**Comment by irrKopf** [comment]
> Hey IrrKopf,
> 
> This error seems to be happening inside NMS. I'm not sure I can do anything about it.

I test the setup in detail to see if it restricts me in any way.
Maybe I'll come up with the solution too. The only important thing is that everything works 100%, as I will soon be traveling through spain.
If I know something about the error, I'll write it here

**Comment by irrKopf** [comment]
I got it... Just Reinstall the NMS to Neewer Version in Console.
Thx
