### ISSUE TITLE
Connection failed: java.net.connectexception: failed to connect to /[IP] 

### ISSUE THREAD

**Issue by Perceivingmind** [715209/nginx-obs-automatic-low-bitrate-switching#64]
This is the first time I am trying to set up something on from github that worked for me questioning I have my setups right.
I've tried to setup something for Valheim and a websocket but never worked so didn't pull through.

This is the first time I was able to work with instruction on github where everything worked:
Streaming from phone to OBS RTMP, auto switch scenes, twitch command recognition.
Until, I tried to do it not on wifi. When I try to use 4G network the app I use (streamlabs mobile) gives me this problem:

Connection failed:
java.net.ConnectEcxeption: failed to connect to /[IPADRES] (port 1935) from /:: (port 39016): connect failed: ETIMEDOUT (Connection timed out)

I am trying to figure out myself atm. But thought in meanwhile I'll post it here if someone had this problem too and can help me with figuring this out.

PSP. I have a ZTE H369A modem.

**Comment by 715209** [comment]
Hello  @Perceivingmind,

It might not be able to connect on a 4G network because:

1. You are using your local ip address.
2. Haven't port forwarded port 1935.

**Comment by Perceivingmind** [comment]
Hi @715209 
> 1. You are using your local ip address.
> 2. Haven't port forwarded port 1935.

1. The IP addres you put in there is your pc addres where the image needs to go right? Or is that the public ip address? 
So, the pc where obs is running on. 
When I have rtmp://[PUBLICIP]:1935/publish it gives the same message.

2. I googled and I used https://www.portchecktool.com/ to check if it was ok but none of the ports get through?
Even the standard 25 and 80? (if those are even standard) The site still gives the error "Connection timed out."
But I did set Nginx to 1935

**Comment by 715209** [comment]
1. If you are using 4G you should use your public IP address (you can find this on something like https://ipinfo.io/)
2. That means you haven't port forwarded yet. @b3ck has a tutorial on this (https://youtu.be/rglDAIm73cM?t=814) but each router has their own UI so it can look different for you.

**Comment by Perceivingmind** [comment]
1. I tried the public ip 77.x.x.x too  but this gives the same message but on 4G
I also saw this on that website.

 privacy: Object
 hosting: false
 
Shouldn't hosting be true instead of false? I thought I read something about that yesterday.
 I feel this is a modem issue but I don't know where to look at. Maybe I need to open up a port or gate? Or allow something. The video you send you have to enable Port forwarding even after you put the ports in. But I don't see any of that here.
 
 I have a ZTE H369A modem and a Sitecom wireless gigabit router 300N in between. If I test with wifi it's with the router, and everything works. But with 4G I tried with and without router, and both the connection times out for me.

**Comment by 715209** [comment]
No the hosting stuff doesn't matter on that page. I think your problem is just with port forwarding once you've done that everything should work. This website might help you with that (https://portforward.com/).

If your computer running NGINX is connected through both modem/router you probably have to port forward from both of them.

**Comment by Perceivingmind** [comment]
I followed the steps on portforward.com I even used the portchecker by them but somehow it says my port is not open or not reachable. I will try again but without the router in between. To see if that is the problem. 

This video is more how it looks like for my modem (it's in dutch tho) and it seems to be that I am doing the same steps for that modem.
https://www.youtube.com/watch?v=KSlPQgZT4QU but it's 3am :'d and I need sleep

**Comment by 715209** [comment]
If you want I can try to set it up for you contact me on discord 715209#0600
