### ISSUE TITLE
Help Please

### ISSUE THREAD

**Issue by Itzch** [715209/nginx-obs-automatic-low-bitrate-switching#7]
Sorry i am new to this stuff But I have a problem

x Error [NGINX] Error Fetching Stats 

No idea how to fix that

**Comment by b3ck** [comment]
@Itzch You have to make sure your RTMP server is running and configured correctly in your config file, if you could paste your config in a reply with the private bits replaced with X's that would help.


Kind Regards,
-b3ck

**Comment by Itzch** [comment]
What do you mean by Private Bits Sorry i am new to this site 
Thanks For your Help
[nginx0001.txt](https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/files/3064417/nginx0001.txt)

**Comment by b3ck** [comment]
Just things like IP Address, passwords etc.. I see your attached config file, this is your current NGINX config file? if so you will need to use the provided NGINX config file provided in this Git, or modify your current NGINX to match the settings needed for the script to properly run.

ex; your current RTMP config in your NGINX config is currently this:
```
rtmp {
        server {
                listen 1935;
                chunk_size 8192;

                application live {
                        live on;
                        record off;
                }
        }
}
```

you would need to replace those lines with these lines;

```
rtmp {
    server {
        listen 1935;
        ping 30s;
        notify_method get;
        chunk_size 8192;
        ack_window 8192;

        # Stream to "rtmp://IPHERE/publish/live".
        application publish {
            live on;
            wait_video on;
            wait_key on;
            exec_options on;
            publish_notify on;
            play_restart on;
            drop_idle_publisher 6s;
            idle_streams off;
        }
    }
}
```
Then you would will also need to make sure the provided 'stat.xsl' is in this directory 'Users/Itzch/Desktop/Nginx/'

Let me know if you have any further questions.


Kind Regards,
-b3ck

**Comment by Itzch** [comment]
after i change the line you provide i can't send signal to rtmp-obs. same thing happen to your Conf File that's on the nginx obs automatic folder

**Comment by b3ck** [comment]
after you update the file you have to send your RTMP to:

`rtmp://YOUR-IP:PORT/publish/live`

or

`rtmp://YOUR-IP:PORT/publish/`
`stream key: live`

**Comment by Itzch** [comment]
Do you Have email or Discord?

**Comment by b3ck** [comment]
that line should be this:

`# Stream to "rtmp://IPHERE/publish/live".`

This is a commented line only shown as an example, you do not change it, it is used to guide you for the streaming app you use.

I would give you my discord but I would like to keep it on here just in case others are having the same issue and to help them better understand issues and fixes.


Kind Regards,
-b3ck

**Comment by Itzch** [comment]
Thanks for Replying.
I know What you mean but still can i have it? to send you my files incase i did something wrong

**Comment by 715209** [comment]
Do you have the same RTMP set in the config?
If you have, could you try going to `http://YOURIPHERE/stats` and see if the page works.

**Comment by Itzch** [comment]
Umm The Page Can Load But All White No text Or Anything

**Comment by 715209** [comment]
Change that to `root "C:/Users/Itzch/Desktop/nginx/";` then it should work.

**Comment by Itzch** [comment]
Everything almost work 

This Keep  Happen
![image](https://user-images.githubusercontent.com/48471083/56100427-1d48b180-5f4b-11e9-86da-547d60ed82af.png

**Comment by 715209** [comment]
It looks like it's working.

**Comment by Itzch** [comment]
Yep,It's Working But The  Error Receiving Current Bitrate keep switch to offline while my phone is sending Data To Rtmp

**Comment by b3ck** [comment]
Did you add OBS websocket and configure that properly?

**Comment by Itzch** [comment]
I figured it out it was the worker processes in the nginx config Files.

From:
`worker_processes  2;`

to:
`worker_processes  1;`

After i did this it was Fixed
