### ISSUE TITLE
Can not See / Connect to Stream

### ISSUE THREAD

**Issue by Nevs08** [715209/nginx-obs-automatic-low-bitrate-switching#70]
Hi,

i successfully Configurated everything. Everything is working... Chat Commands, Scene Switching and Connecting to rtmp Server via Streamelemtents App on Android and also GoPro. 

But in my OBS isnt any Stream showing up. And in VLC it shows me: avcodec error: Failed to open rtmp://localhost:1935/publish/live: Operation not permitted

What i am doing wrong?

Best wishes, 
Nevs08

**Comment by b3ck** [comment]
What URL are you using to pull the stream into OBS? Also are you using VLC Video Source or the default Media Source in OBS?

**Comment by Nevs08** [comment]
I "fixed" it...

In the config.json File i changed the rtmp Key from live to someting else and this didnt let me connect to rtmp://localhost:1935/publish/live 

I just changed it back to live and its working now.

**Comment by b3ck** [comment]
Copy that, you should be able to change the Key in the config and in OBS and it should work. just FYI.
