### ISSUE TITLE
No Stats but Stream running - No automatic switching

### ISSUE THREAD

**Issue by logmask** [715209/nginx-obs-automatic-low-bitrate-switching#73]
Hey,

i setup nginx + automatic switching on a ubuntu vps. obs is running at home on a windows computer.

so far it is all working, i can connect to the rtmp, i can switch scenes through twitch chat etc.

But: i can not see any !bitrate, !sourceinfo or !obsinfo in chat.
The stat page is working and can be accessed.

i dont know how to fix it?

14:48 me: !sourceinfo 
14:48 bot: [SRC] offline 
14:48 me: !obsinfo 
14:48 bot: [OBS] offline 
14:49 me: !bitrate 
14:49 bot: Current bitrate: offline 

[7/7/2021] [2:03:19 PM] [OBS] › ℹ  info      Connecting & authenticating
[7/7/2021] [2:03:19 PM] [CHT] › ℹ  info      Connecting to twitch
[7/7/2021] [2:03:19 PM] [OBS] › ✔  success   Successfully connected
[7/7/2021] [2:03:20 PM] [CHT] › ✔  success   Successfully Connected
[7/7/2021] [2:03:20 PM] [CHT] › ✔  success   Authenticating and joining channel #me

config.json:
changed several times, from standard nginx to ip of nginx server from localhost/stat to ip/stat etc. etc. nothing changed there.

at the moment it is like this:

  "rtmp": {
        "server": "rtmp://IP:1935/publish/live",
        "stats": "http://IP/stat",
        "application": "publish",
        "key": "live"
    },

can anyone help here?
![1bb4253e74621fa5515fbd56c121df8c](https://user-images.githubusercontent.com/87076671/124768327-ddf64900-df38-11eb-8aea-f499adeef0b4.png)

**Comment by logmask** [comment]
Sorry attached are my current config files.
[nginx.config.txt](https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/files/6777868/nginx.config.txt)
[config.json-.txt](https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/files/6777879/config.json-.txt)

**Comment by 715209** [comment]
Hey @logmask ,

Are you streaming from OBS?

**Comment by logmask** [comment]
yes, OBS is running on windows on local pc

noalbs + nginx / node media server is on a ubuntu vps connecting through websocket to the obs on the computer

connection is fine, because i can change all scenes etc.

but i do not get any stats displayed in chat - also the switching is not working because there are no stats.

i just closed nginx server and started the built in node media server. i can connect with my mobile phone the rtmp stream. i can include it in obs. but i can not get any bitrate information etc. for automatic switichting and chat info.


this is right now with the built in node media server:

18:41 logmask: !b 
18:41 logbotz: Current bitrate: offline 
18:41 logmask: !s 
18:41 logbotz: [SRC] offline 
18:41 logmask: !o 
18:41 logbotz: [OBS] offline 

http://IP:8000/api/streams : 

{"publish":{"live":{"publisher":{"app":"publish","stream":"live","clientId":"ID","connectCreated":"2021-07-07T16:41:40.821Z","bytes":17926089,"ip":"IP","audio":{"codec":"AAC","profile":"LC","samplerate":44100,"channels":1},"video":{"codec":"H264","width":1280,"height":720,"profile":"Baseline","level":3.1}},"subscribers":[]}}}

**Comment by 715209** [comment]
When you are streaming from OBS it should work, like actually streaming to twitch.
