### ISSUE TITLE
Question: How to show current Bitrate in OBS

### ISSUE THREAD

**Issue by TheFrodo** [715209/nginx-obs-automatic-low-bitrate-switching#75]
Hello Everyone,

How can i show the current Bitrate from that RTMP Stream in OBS?
Is It Possible?

That would be Nice <3

**Comment by 715209** [comment]
Hello TheFrodo,

You can use this https://github.com/b3ck/server-bitrate-html

**Comment by TheFrodo** [comment]
Thank You <3
