### ISSUE TITLE
"http://localhost/stat" does not show any stats

### ISSUE THREAD

**Issue by Tinteex** [715209/nginx-obs-automatic-low-bitrate-switching#77]
Hello, 
the stream and obs remote are working fine.
Sadly i cant see any stats on this adress.

**Comment by DeeDeeLP** [comment]
That is completely normal. But if you want to see the stats -> Press F12 on your keyboard and switch to the sources tab, select the stat file on the left menu and there you can see the stats in the code section. You'll have to refresh the page to see updates on the stats, but at least you can see them. 

Greetings.
