### ISSUE TITLE
Offline Switching not working

### ISSUE THREAD

**Issue by mschmidt291** [715209/nginx-obs-automatic-low-bitrate-switching#8]
When the stream is stopped via OBS, the NodeJS Application is not recognizing it and thus is not changing the scene to the configured one.

**Comment by b3ck** [comment]
Did you want it to default to a certain scene when the stream shuts down?  I'm sure 715209 could add that =)

**Comment by mschmidt291** [comment]
I completely misunderstood, that you *have* to be streaming with OBS. I thought the Application will change scenes even if you're not streaming.

**Comment by 715209** [comment]
Yes this has been changed in the current version.
Previously it would just keep changing but that made it force you to stop the app.
