### ISSUE TITLE
Add  RTMP+SRT simultaneously Monitor ?

### ISSUE THREAD

**Issue by Ladelltwitch** [715209/nginx-obs-automatic-low-bitrate-switching#80]
GREAT PIECE OF SOFTWARE. THANK YOU SO MUCH!!!

I use Google Translate

Want to ask if RTMP and SRT simultaneously Monitor 
if not go to BRB?

**Comment by b3ck** [comment]
Yes that is possible when using the pre-lease version of NOALBS v2.2.1: https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/releases/tag/v2.2.1


Kind Regards,
-b3ck
