### ISSUE TITLE
refresh scene?

### ISSUE THREAD

**Issue by Blackwolf8202** [715209/nginx-obs-automatic-low-bitrate-switching#83]
Hi, how do I add the refresh scene to the config? Because when you write !R, the video only turns black and then it goes back to the same video. So it does not change scene in between when updating? // Tony

**Comment by 715209** [comment]
Hi Blackwolf8202,

The refresh scene is not used anymore in v2, !refresh or !fix should solve any issues.

**Comment by Blackwolf8202** [comment]
aha okay thanks =)
