### ISSUE TITLE
There is no sound after rebooting the phone or the encoder

### ISSUE THREAD

**Issue by UnisonRU** [715209/nginx-obs-automatic-low-bitrate-switching#9]
There is no sound in "normalScene" after rebooting the device (Phone or HDMI Encoder). In "refreshScene" and "lowBitrateScene" there is sound. Only restarting the OBS helps.

In the mixer of scene "normalScene", there is sound and is listened through OBS. But on the broadcast of this scene there is no sound. This happens only if you restart the broadcast device (Phone or HDMI Encoder).

**Comment by Itzch** [comment]
Try use VLC Video Source

**Comment by UnisonRU** [comment]
Yes, I just did it. It worked :)

**Comment by b3ck** [comment]
👍
