### ISSUE TITLE
!fix just 'black-screen' and picture never comes back again.

### ISSUE THREAD

**Issue by DigibitDK** [715209/nginx-obs-automatic-low-bitrate-switching#91]
After a lot of testing, i'm not able to make !fix work.
Everything works perfect, except !fix, it blanks the picture, but never returns back :(

I can see in Nginx that OBS still pulls the RTMP-feed, but shows nothing afterwards. Everything is setup accordingly to your guides, and I have even tried your default nginx-conf.

Im testing with 'Media-Source', since i'm still expecting that 'Media-Source' should be used insted of VLC.

It kind of worked i V1, but not as good as refresh did. Im aware that the behavior of !fix now probably has changed compared to V1.

In V1, the bot announced in chat, that it was trying to fix, and then a confirm message. Now I only get a trying to fix, but no confirm or anything at all ...
^^ (This is confirmed as expected behavior in v2) 

Tested on latest NGINX+RTMP Module.
Noalbs v2.5.1
OBS 27.1.3
Websocket 4.9.1

**Comment by b3ck** [comment]
In v2 it just says in chat that it's trying to fix it and that's it, it restarts all SRT and RTMP Sources in OBS, can you share a screenshot of your Media Source Properties window? you can redact any confidential information you like.

**Comment by DigibitDK** [comment]
I have provided 715209 with a lot of documentation back in February, but we did not come to any conclusion on the issue.

It seems to work for some, and not for others. I have tried to change RTMP-server, config, OBS, PC etc. And still the same for me.

**Comment by TabbieTV** [comment]
Would it work if you went back to the Refreshscene during the !fix ?
haven't used this for some time now, and refresh scene is gone now, and it used to fix almost everything before.
Just a dumb thought from someone with no codin experience
