### ISSUE TITLE
!fix sticks on black screen

### ISSUE THREAD

**Issue by Barrikin** [715209/nginx-obs-automatic-low-bitrate-switching#94]
Issuing a !fix command makes the screen go black but never goes back to the live obs scene. Have to manually switch.

```
Mar 22 01:16:28 srt noalbs[2186177]: 2022-03-22T01:16:28.622824Z  INFO noalbs::chat::chat_handler: [otr_penguin] barrikin executed command: Fix
Mar 22 01:16:48 srt noalbs[2186177]: 2022-03-22T01:16:48.948354Z  INFO noalbs::chat::chat_handler: [otr_penguin] barrikin executed command: PrivacyScene
Mar 22 01:17:08 srt noalbs[2186177]: 2022-03-22T01:17:08.295965Z  INFO noalbs::chat::chat_handler: [otr_penguin] barrikin executed command: LiveScene
```

**Comment by DigibitDK** [comment]
I have the same experience - No solution found after A LOT of testing.

I already have an issue open on that: https://github.com/715209/nginx-obs-automatic-low-bitrate-switching/issues/91

**Comment by b3ck** [comment]
Issuing the !f or !fix command doesn't change the scene in v2, it just resets all SRT and RTMP media sources.  Can you share a screenshot of your Media Source Properties window? you can redact any confidential information you like.

**Comment by Barrikin** [comment]
![srt feed](https://user-images.githubusercontent.com/54464128/161398117-8b870b10-5dbb-4520-82da-d6be4c9459b2.png)

**Comment by b3ck** [comment]
hmm.. everything looks good there.. I don't suppose there is a way for you show it happening is there?  Any errors in the OBS log?

**Comment by DigibitDK** [comment]
@Barrikin I can confirm, that this issue is fix in the next release :)
